In [718]:
# Dependencies
import os
import pandas as pd

In [719]:
# Create csv_path variable
csv_path = os.path.join('HeroesOfPymoli','Resources', 'purchase_data.csv')

# Read with pandas
purchase_frame = pd.read_csv(csv_path)
purchase_frame.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [720]:
### Player Count
# Total Number of Unique Playes
player_count = len(purchase_frame['SN'].unique())
player_count

576

In [721]:
### Purchasing Analysis
# Number of Unique Items
unique_items = len(purchase_frame['Item Name'].unique())
# Average Price
avg_price = round(purchase_frame['Price'].mean(), 2)
# Total Number of Purchases
purchase_total = len(purchase_frame)
# Total Revenue
total_revenue = round(purchase_frame['Price'].sum(), 2)
purchase_analysis = dict({'Unique Items':unique_items,'Average Price':f"${avg_price}",'Total Purchases':purchase_total,'Total Revenue':f"${total_revenue}"})
purchase_analysis

{'Unique Items': 179,
 'Average Price': '$3.05',
 'Total Purchases': 780,
 'Total Revenue': '$2379.77'}

In [722]:
### Gender Demographics
# Male Count 
gender_list = purchase_frame['Gender'].unique()
gender_list

array(['Male', 'Other / Non-Disclosed', 'Female'], dtype=object)

In [723]:
gender_demo = dict()
for gender in gender_list:
    tempframe = purchase_frame.loc[purchase_frame['Gender'] == gender]
    count = len(tempframe['SN'].unique())
    gender_demo[f"{gender} Count"] = count
    gender_demo[f"{gender} Percentage"] = f"{round((count/player_count*100),2)}%"
gender_demo

{'Male Count': 484,
 'Male Percentage': '84.03%',
 'Other / Non-Disclosed Count': 11,
 'Other / Non-Disclosed Percentage': '1.91%',
 'Female Count': 81,
 'Female Percentage': '14.06%'}

In [724]:
def analysis(df):
    analysis = dict()
    analysis['Purchase Count'] = len(df)
    analysis['Average Purchase Price'] = f"${round(df['Price'].mean(), 2)}"
    analysis['Total Purchase Value'] = f"${round(df['Price'].sum(), 2)}"
    per_person = pd.DataFrame()
    players = df['SN'].unique()
    i = 0
    total = 0
    for player in players:
        tempframe = df.loc[df['SN'] == player]
        total = total + tempframe['Price'].sum()
        i = i + 1
    analysis['Average Purchase Total'] = f"${round(total/i,2)}"
    return analysis

In [725]:
gender_breakdown = dict()
for gender in gender_list:
    tempframe = purchase_frame.loc[purchase_frame['Gender'] == gender]
    gender_breakdown[gender] =  analysis(tempframe)
gender_breakdown

{'Male': {'Purchase Count': 652,
  'Average Purchase Price': '$3.02',
  'Total Purchase Value': '$1967.64',
  'Average Purchase Total': '$4.07'},
 'Other / Non-Disclosed': {'Purchase Count': 15,
  'Average Purchase Price': '$3.35',
  'Total Purchase Value': '$50.19',
  'Average Purchase Total': '$4.56'},
 'Female': {'Purchase Count': 113,
  'Average Purchase Price': '$3.2',
  'Total Purchase Value': '$361.94',
  'Average Purchase Total': '$4.47'}}

In [726]:
# Print out max age and min age from dataset to create correct age groups
ages = purchase_frame['Age'].unique()
print(f"Max Age: {max(ages)}, Min Age: {min(ages)}")

Max Age: 45, Min Age: 7

In [727]:
### Age Demographics
# Age ranges 
age_ranges = ["0-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-59"]
age_demographics = dict()
for age_range in age_ranges:
    parts = age_range.split('-')
    start = int(parts[0])
    end = int(parts[1])
    tempframe = purchase_frame.loc[(purchase_frame['Age'] >= start) & (purchase_frame['Age'] <= end)] 
    age_demographics[age_range] = analysis(tempframe)
age_demographics

{'0-9': {'Purchase Count': 23,
  'Average Purchase Price': '$3.35',
  'Total Purchase Value': '$77.13',
  'Average Purchase Total': '$4.54'},
 '10-14': {'Purchase Count': 28,
  'Average Purchase Price': '$2.96',
  'Total Purchase Value': '$82.78',
  'Average Purchase Total': '$3.76'},
 '15-19': {'Purchase Count': 136,
  'Average Purchase Price': '$3.04',
  'Total Purchase Value': '$412.89',
  'Average Purchase Total': '$3.86'},
 '20-24': {'Purchase Count': 365,
  'Average Purchase Price': '$3.05',
  'Total Purchase Value': '$1114.06',
  'Average Purchase Total': '$4.32'},
 '25-29': {'Purchase Count': 101,
  'Average Purchase Price': '$2.9',
  'Total Purchase Value': '$293.0',
  'Average Purchase Total': '$3.81'},
 '30-34': {'Purchase Count': 73,
  'Average Purchase Price': '$2.93',
  'Total Purchase Value': '$214.0',
  'Average Purchase Total': '$4.12'},
 '35-39': {'Purchase Count': 41,
  'Average Purchase Price': '$3.6',
  'Total Purchase Value': '$147.67',
  'Average Purchase Total': '$4.76'},
 '40-44': {'Purchase Count': 12,
  'Average Purchase Price': '$3.04',
  'Total Purchase Value': '$36.54',
  'Average Purchase Total': '$3.32'},
 '45-59': {'Purchase Count': 1,
  'Average Purchase Price': '$1.7',
  'Total Purchase Value': '$1.7',
  'Average Purchase Total': '$1.7'}}

In [728]:
# For refernce
purchase_frame.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [729]:
### Top Spenders
# Group dataframe by SN and drop everything but Price
grouped_frame = pd.DataFrame()
grouped_frame = purchase_frame.groupby(['SN'], as_index=False).sum().sort_values(['Price'], ascending=False)
top_five = grouped_frame.head(5)
players = top_five['SN'].unique()
topfive_output = dict()
i = 1
for player in players: 
    tempdict = dict()
    tempframe = purchase_frame.loc[purchase_frame['SN'] == player]
    purchase_count = len(tempframe)
    avg_price = tempframe['Price'].mean()
    total_value = tempframe['Price'].sum()
    tempdict['SN'] = player
    tempdict['Purchase Count'] = purchase_count
    tempdict['Average Purchase Price'] = round(avg_price, 2)
    tempdict['Total Purchase Value'] = round(total_value, 2)
    topfive_output[i] = tempdict
    i = i+1
topfive_output

{1: {'SN': 'Lisosia93',
  'Purchase Count': 5,
  'Average Purchase Price': 3.79,
  'Total Purchase Value': 18.96},
 2: {'SN': 'Idastidru52',
  'Purchase Count': 4,
  'Average Purchase Price': 3.86,
  'Total Purchase Value': 15.45},
 3: {'SN': 'Chamjask73',
  'Purchase Count': 3,
  'Average Purchase Price': 4.61,
  'Total Purchase Value': 13.83},
 4: {'SN': 'Iral74',
  'Purchase Count': 4,
  'Average Purchase Price': 3.4,
  'Total Purchase Value': 13.62},
 5: {'SN': 'Iskadarya95',
  'Purchase Count': 3,
  'Average Purchase Price': 4.37,
  'Total Purchase Value': 13.1}}

In [730]:
### Most Popular Items
grouped_frame = purchase_frame.groupby(['Item ID'], as_index=False).size().sort_values([1], ascending=False)
grouped_frame

TypeError: unhashable type: 'list'