In [120]:
# Dependencies
import os
import pandas as pd

In [121]:
# Create csv_path variable
csv_path = os.path.join('HeroesOfPymoli','Resources', 'purchase_data.csv')

# Read with pandas
purchase_frame = pd.read_csv(csv_path)
purchase_frame.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [122]:
### Player Count
# Total Number of Unique Playes
player_count = len(purchase_frame['SN'].unique())
player_count

576

In [123]:
### Purchasing Analysis
# Number of Unique Items
unique_items = len(purchase_frame['Item Name'].unique())
# Average Price
avg_price = round(purchase_frame['Price'].mean(), 2)
# Total Number of Purchases
purchase_total = len(purchase_frame)
# Total Revenue
total_revenue = round(purchase_frame['Price'].sum(), 2)
purchase_analysis = pd.DataFrame({"Unique Items": [unique_items],
                                  "Average Price": f"${avg_price}",
                                  "Total Purchases": [purchase_total],
                                  "Total Revenue": f"${total_revenue}"})
purchase_analysis

   Unique Items Average Price  Total Purchases Total Revenue
0           179         $3.05              780      $2379.77

In [124]:
index_list = []
columns = ['Total Count', 'Percentage of Players']
data = []
gender_list = purchase_frame['Gender'].unique()
for gender in gender_list:
    tempframe = purchase_frame.loc[purchase_frame['Gender'] == gender]
    data.append([len(tempframe['SN'].unique()),f"{round(len(tempframe['SN'].unique())/player_count * 100,2)}%"])
    index_list.append(gender)
gender_demo = pd.DataFrame(columns=columns,data=data)    
gender_demo.index = index_list
gender_demo.sort_values(by='Total Count', ascending=False, inplace=True)
gender_demo

                       Total Count Percentage of Players
Male                           484                84.03%
Female                          81                14.06%
Other / Non-Disclosed           11                 1.91%

In [125]:
# Create purchasing analysis function to handle repetitive calculations
def purchasing_analysis(segment):
    columns = ['Purchase Count', 'Average Purchase Price', 'Total Purchase Value', 'Average Purchase Total']
    segment_list = purchase_frame[segment].unique()
    data = []
    for s in segment_list:
        tempframe = purchase_frame.loc[purchase_frame[segment] == s]
        purchase_count = len(tempframe)
        person_count = len(tempframe['SN'].unique())
        avg_purchase = tempframe['Price'].mean()
        total_purchase = tempframe['Price'].sum()
        avg_purchase_pp = round(total_purchase/person_count,2)
        data.append([purchase_count,avg_purchase,total_purchase,avg_purchase_pp])
    output = pd.DataFrame(columns=columns,data=data)
    output.index = segment_list
    output.index.name = segment
    return output

In [126]:
# Use function with 'Gender' segment
gender_analysis = purchasing_analysis('Gender')
gender_analysis.sort_values(by='Purchase Count', ascending=False, inplace=True)
gender_analysis

,Purchase Count,Average Purchase Price,Total Purchase Value,Average Purchase Total
Gender,,,,
Male,652,3.017853,1967.64,4.07
Female,113,3.203009,361.94,4.47
Other / Non-Disclosed,15,3.346000,50.19,4.56

In [127]:
# Print out max age and min age from dataset to create correct age groups
ages = purchase_frame['Age'].unique()
print(f"Max Age: {max(ages)}, Min Age: {min(ages)}")

Max Age: 45, Min Age: 7

In [128]:
### Age Demographics
# Age ranges 
labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40+']
bins = ['0','9','14','19','24','29','34','39','45']
purchase_frame["Age Range"] = pd.cut(purchase_frame['Age'], bins, labels=labels)
## 7 YEARS OLD DOES NOT FALL INTO CORRECT BIN WHATTTT

In [129]:
# For refernce
purchase_frame

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Range
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
...,...,...,...,...,...,...,...,...
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,92,Final Critic,4.19,NaN
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [130]:
age_analysis = purchasing_analysis('Age Range')
age_analysis

,Purchase Count,Average Purchase Price,Total Purchase Value,Average Purchase Total
Age Range,,,,
20-24,365,3.052219,1114.06,4.32
40+,13,2.941538,38.24,3.19
35-39,41,3.601707,147.67,4.76
30-34,73,2.931507,214.00,4.12
25-29,101,2.900990,293.00,3.81
<10,68,3.156029,214.61,3.70
NaN,0,NaN,0.00,NaN
15-19,96,2.927708,281.06,3.47

In [131]:
player_analysis = purchasing_analysis('SN')
player_analysis.sort_values(by='Purchase Count', ascending=False, inplace=True)
player_analysis.drop(labels=['Average Purchase Total'], axis=1, inplace=True)
player_analysis.head(5)

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                 5                3.792000                 18.96
Iral74                    4                3.405000                 13.62
Idastidru52               4                3.862500                 15.45
Lisim78                   3                3.340000                 10.02
Aina42                    3                3.073333                  9.22