In [2]:
# Dependencies 
import pandas as pd 
import os

In [4]:
# Create paths to CSVs
csvpath_schools = os.path.join('PyCitySchools', 'Resources', 'schools_complete.csv')
csvpath_students = os.path.join('PyCitySchools', 'Resources', 'students_complete.csv')

In [6]:
# Create School DataFrame
school_frame = pd.read_csv(csvpath_schools)
school_frame.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [8]:
# Create Student DataFrame
student_frame = pd.read_csv(csvpath_students)
student_frame.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [ ]:
### District Summary 
district_summary = pd.DataFrame()
total_schools = len(school_frame['school_name'].unique())
total_students = len(student_frame['student_name'].unique())
total_budget = school_frame['budget'].sum()
avg_math_scare = student_frame['math_score'].mean()
avg_reading_score = student_frame['reading_score'].mean()
pass_math_frame = student_frame.loc[student_frame['math_score'] >= 70]
passing = len(pass_math_frame['student_name'].unique())
percent_passing_math = passing/total_students*100
fail_math_frame = student_frame.loc[student_frame['math_score'] < 70]
failing = len(fail_math_frame['student_name'].unique())
percent_failing_math = failing/total_students*100